version: "3"

tasks:
    run-local:
        desc: "Run service on a local machine"
        cmds:
            - go run ./cmd/main.go --config ./config/local.yml
    test:
        desc: "Run all rests"
        cmds:
            - go clean -testcache
            - gotestsum --format-hide-empty-pkg --format-icons hivis -- -coverprofile=cover.out ./...
    mockgen:
        desc: "Generate all mocks"
        cmds:
            - rm -rf internal/util/mocks/*
            - mockgen -source=internal/repository/assignment/repository.go -destination=internal/util/mocks/mock_assignment_repository.go -package mocks -mock_names Repository=AssignmentRepository Repository
