// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: assignment.proto

package client

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignmentFindByFormIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FormId string `protobuf:"bytes,1,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
}

func (x *AssignmentFindByFormIDRequest) Reset() {
	*x = AssignmentFindByFormIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assignment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignmentFindByFormIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentFindByFormIDRequest) ProtoMessage() {}

func (x *AssignmentFindByFormIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentFindByFormIDRequest.ProtoReflect.Descriptor instead.
func (*AssignmentFindByFormIDRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{0}
}

func (x *AssignmentFindByFormIDRequest) GetFormId() string {
	if x != nil {
		return x.FormId
	}
	return ""
}

type AssignmentFindByFormIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupIds []string `protobuf:"bytes,1,rep,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
}

func (x *AssignmentFindByFormIDResponse) Reset() {
	*x = AssignmentFindByFormIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assignment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignmentFindByFormIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentFindByFormIDResponse) ProtoMessage() {}

func (x *AssignmentFindByFormIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentFindByFormIDResponse.ProtoReflect.Descriptor instead.
func (*AssignmentFindByFormIDResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{1}
}

func (x *AssignmentFindByFormIDResponse) GetGroupIds() []string {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

type AssignmentFindByGroupIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *AssignmentFindByGroupIDRequest) Reset() {
	*x = AssignmentFindByGroupIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assignment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignmentFindByGroupIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentFindByGroupIDRequest) ProtoMessage() {}

func (x *AssignmentFindByGroupIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentFindByGroupIDRequest.ProtoReflect.Descriptor instead.
func (*AssignmentFindByGroupIDRequest) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{2}
}

func (x *AssignmentFindByGroupIDRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type AssignmentFindByGroupIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FormIds []string `protobuf:"bytes,1,rep,name=form_ids,json=formIds,proto3" json:"form_ids,omitempty"`
}

func (x *AssignmentFindByGroupIDResponse) Reset() {
	*x = AssignmentFindByGroupIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_assignment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignmentFindByGroupIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentFindByGroupIDResponse) ProtoMessage() {}

func (x *AssignmentFindByGroupIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentFindByGroupIDResponse.ProtoReflect.Descriptor instead.
func (*AssignmentFindByGroupIDResponse) Descriptor() ([]byte, []int) {
	return file_assignment_proto_rawDescGZIP(), []int{3}
}

func (x *AssignmentFindByGroupIDResponse) GetFormIds() []string {
	if x != nil {
		return x.FormIds
	}
	return nil
}

var File_assignment_proto protoreflect.FileDescriptor

var file_assignment_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x42, 0x0a, 0x1d, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69,
	0x6e, 0x64, 0x42, 0x79, 0x46, 0x6f, 0x72, 0x6d, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x21, 0x0a, 0x07, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x72, 0x03, 0xb0, 0x01, 0x01, 0x52, 0x06, 0x66, 0x6f,
	0x72, 0x6d, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x1e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x46, 0x6f, 0x72, 0x6d, 0x49, 0x44, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x64, 0x73, 0x22, 0x45, 0x0a, 0x1e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x72, 0x03, 0xb0, 0x01,
	0x01, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x1f, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x66, 0x6f, 0x72, 0x6d, 0x49, 0x64, 0x73, 0x32, 0xc1, 0x01, 0x0a, 0x0a, 0x41, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x57, 0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x64, 0x42,
	0x79, 0x46, 0x6f, 0x72, 0x6d, 0x49, 0x44, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x46, 0x6f,
	0x72, 0x6d, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6e, 0x64,
	0x42, 0x79, 0x46, 0x6f, 0x72, 0x6d, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x5a, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x44, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1e, 0x5a, 0x1c,
	0x75, 0x70, 0x61, 0x73, 0x73, 0x65, 0x64, 0x2e, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x76, 0x31, 0x3b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_assignment_proto_rawDescOnce sync.Once
	file_assignment_proto_rawDescData = file_assignment_proto_rawDesc
)

func file_assignment_proto_rawDescGZIP() []byte {
	file_assignment_proto_rawDescOnce.Do(func() {
		file_assignment_proto_rawDescData = protoimpl.X.CompressGZIP(file_assignment_proto_rawDescData)
	})
	return file_assignment_proto_rawDescData
}

var file_assignment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_assignment_proto_goTypes = []any{
	(*AssignmentFindByFormIDRequest)(nil),   // 0: api.AssignmentFindByFormIDRequest
	(*AssignmentFindByFormIDResponse)(nil),  // 1: api.AssignmentFindByFormIDResponse
	(*AssignmentFindByGroupIDRequest)(nil),  // 2: api.AssignmentFindByGroupIDRequest
	(*AssignmentFindByGroupIDResponse)(nil), // 3: api.AssignmentFindByGroupIDResponse
}
var file_assignment_proto_depIdxs = []int32{
	0, // 0: api.Assignment.FindByFormID:input_type -> api.AssignmentFindByFormIDRequest
	2, // 1: api.Assignment.FindByGroupID:input_type -> api.AssignmentFindByGroupIDRequest
	1, // 2: api.Assignment.FindByFormID:output_type -> api.AssignmentFindByFormIDResponse
	3, // 3: api.Assignment.FindByGroupID:output_type -> api.AssignmentFindByGroupIDResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_assignment_proto_init() }
func file_assignment_proto_init() {
	if File_assignment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_assignment_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AssignmentFindByFormIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_assignment_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AssignmentFindByFormIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_assignment_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AssignmentFindByGroupIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_assignment_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AssignmentFindByGroupIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_assignment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assignment_proto_goTypes,
		DependencyIndexes: file_assignment_proto_depIdxs,
		MessageInfos:      file_assignment_proto_msgTypes,
	}.Build()
	File_assignment_proto = out.File
	file_assignment_proto_rawDesc = nil
	file_assignment_proto_goTypes = nil
	file_assignment_proto_depIdxs = nil
}
